version: 2

jobs:
    build:
        docker:
            - image: rikorose/gcc-cmake

        working_directory: ~/MeadowsECS

        steps:
            - checkout
            - run:
                command: |
                    mkdir ~/build
                    mkdir -p ~/release/lib
                    cp -R include ~/release
                    cd ~/build
                    cmake -G"Unix Makefiles" -DBUILD_SHARED_LIBS=ON -DBUILD_TEST=ON ~/MeadowsECS
            - run:
                command: |
                    cd ~/build
                    make -j2 MeadowsECS
                    cp libMeadowsECS.so ~/release/lib
            - run:
                command: |
                    mkdir ~/release
                    cd ~/release
                    tar -zcf MeadowsECS-${CIRCLE_BRANCH}-${CIRCLE_BUILD_NUM}.tar.gz ~/release/*
            - run:
                command: |
                    mkdir ~/test-results/junit
                    cd ~/build
                    make -j2 MeadowsECSTest
                    ./test/MeadowsECSTest -r junit > ~/test-results/junit/MeadowsECSTests.xml
            - store_test_results:
                path: ~/test-results
            - store_artifacts:
                path: ~/release