version: 2

jobs:
    build:
        docker:
            - image: rikorose/gcc-cmake

        working_directory: ~/MeadowsECS

        steps:
            - checkout
            - run:
                command: |
                    mkdir ~/build
                    cd ~/build
                    cmake -G"Unix Makefiles" -DBUILD_SHARED_LIBS=OFF -DBUILD_TEST=ON ~/MeadowsECS
            - run:
                command: |
                    cd ~/build
                    make -j2 MeadowsECS
            - persist_to_workspace:
                root: ~/
                paths:
                    - build/*

    test:
        docker:
            - image: rikorose/gcc-cmake

        working_directory: ~/MeadowsECS

        steps:
            - checkout
            - attach_workspace:
                at: ~/
            - run:
                command: |
                    mkdir -p ~/test-results/unit_tests
                    cd ~/build
                    make -j2 MeadowsECSTest
                    ./test/MeadowsECSTest -r junit > ~/test-results/unit_tests/MeadowsECSTest.xml
            - store_test_results:
                path: ~/test-results
